### *Import Libraries*

In [1]:
import pandas as pd
import numpy as np
import functools
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

### *Load Data*

In [2]:
# Read the csv files for the months Jan, Feb, Mar to dataframe quarter1
flight_data = pd.concat(map(functools.partial(pd.read_csv, low_memory = False), ['Jan2019.csv', 'Feb2019.csv','Mar2019.csv']))

### *Inspect Data*

In [3]:
# Call the info() method on flight_data to get the summary of the 
flight_data.shape

(1749234, 78)

In [4]:
# Call the head() method on flight_data to print first five rows
flight_data.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,...,DIV_DISTANCE,DIV1_AIRPORT,DIV1_AIRPORT_ID,DIV1_AIRPORT_SEQ_ID,DIV1_WHEELS_ON,DIV1_TOTAL_GTIME,DIV1_LONGEST_GTIME,DIV1_WHEELS_OFF,DIV1_TAIL_NUM,Unnamed: 77
0,2019,1,1,3,4,2019-01-03,9E,20363,9E,N195PQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019,1,1,4,5,2019-01-04,9E,20363,9E,N919XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019,1,1,5,6,2019-01-05,9E,20363,9E,N316PQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019,1,1,6,7,2019-01-06,9E,20363,9E,N325PQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019,1,1,7,1,2019-01-07,9E,20363,9E,N904XJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Call the info() method on flight_data to get the summary
flight_data.info(verbose = True, null_counts = True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1749234 entries, 0 to 632073
Data columns (total 78 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   YEAR                     1749234 non-null  int64
 1   QUARTER                  1749234 non-null  int64
 2   MONTH                    1749234 non-null  int64
 3   DAY_OF_MONTH             1749234 non-null  int64
 4   DAY_OF_WEEK              1749234 non-null  int64
 5   FL_DATE                  1749234 non-null  object
 6   OP_UNIQUE_CARRIER        1749234 non-null  object
 7   OP_CARRIER_AIRLINE_ID    1749234 non-null  int64
 8   OP_CARRIER               1749234 non-null  object
 9   TAIL_NUM                 1741230 non-null  object
 10  OP_CARRIER_FL_NUM        1749234 non-null  int64
 11  ORIGIN_AIRPORT_ID        1749234 non-null  int64
 12  ORIGIN_AIRPORT_SEQ_ID    1749234 non-null  int64
 13  ORIGIN_CITY_MARKET_ID    1749234 non-null  int64
 14  ORIGIN                   1749234 non-null  object
 15  ORIGIN_CITY_NAME         1749234 non-null  object
 16  ORIGIN_STATE_ABR         1749234 non-null  object
 17  ORIGIN_STATE_FIPS        1749234 non-null  int64
 18  ORIGIN_STATE_NM          1749234 non-null  object
 19  ORIGIN_WAC               1749234 non-null  int64
 20  DEST_AIRPORT_ID          1749234 non-null  int64
 21  DEST_AIRPORT_SEQ_ID      1749234 non-null  int64
 22  DEST_CITY_MARKET_ID      1749234 non-null  int64
 23  DEST                     1749234 non-null  object
 24  DEST_CITY_NAME           1749234 non-null  object
 25  DEST_STATE_ABR           1749234 non-null  object
 26  DEST_STATE_FIPS          1749234 non-null  int64
 27  DEST_STATE_NM            1749234 non-null  object
 28  DEST_WAC                 1749234 non-null  int64
 29  CRS_DEP_TIME             1749234 non-null  int64
 30  DEP_TIME                 1705735 non-null  float64
 31  DEP_DELAY                1705727 non-null  float64
 32  DEP_DELAY_NEW            1705727 non-null  float64
 33  DEP_DEL15                1705727 non-null  float64
 34  DEP_DELAY_GROUP          1705727 non-null  float64
 35  DEP_TIME_BLK             1749234 non-null  object
 36  TAXI_OUT                 1705049 non-null  float64
 37  WHEELS_OFF               1705049 non-null  float64
 38  WHEELS_ON                1703688 non-null  float64
 39  TAXI_IN                  1703688 non-null  float64
 40  CRS_ARR_TIME             1749234 non-null  int64
 41  ARR_TIME                 1703688 non-null  float64
 42  ARR_DELAY                1700782 non-null  float64
 43  ARR_DELAY_NEW            1700782 non-null  float64
 44  ARR_DEL15                1700782 non-null  float64
 45  ARR_DELAY_GROUP          1700782 non-null  float64
 46  ARR_TIME_BLK             1749234 non-null  object
 47  CANCELLED                1749234 non-null  float64
 48  CANCELLATION_CODE        44545 non-null    object
 49  DIVERTED                 1749234 non-null  float64
 50  CRS_ELAPSED_TIME         1749100 non-null  float64
 51  ACTUAL_ELAPSED_TIME      1700782 non-null  float64
 52  AIR_TIME                 1700782 non-null  float64
 53  FLIGHTS                  1749234 non-null  float64
 54  DISTANCE                 1749234 non-null  float64
 55  DISTANCE_GROUP           1749234 non-null  int64
 56  CARRIER_DELAY            330976 non-null   float64
 57  WEATHER_DELAY            330976 non-null   float64
 58  NAS_DELAY                330976 non-null   float64
 59  SECURITY_DELAY           330976 non-null   float64
 60  LATE_AIRCRAFT_DELAY      330976 non-null   float64
 61  FIRST_DEP_TIME           11670 non-null    float64
 62  TOTAL_ADD_GTIME          11670 non-null    float64
 63  LONGEST_ADD_GTIME        11670 non-null    float64
 64  DIV_AIRPORT_LANDINGS     1749234 non-null  int64
 65  DIV_REACHED_DEST         3907 non-null     float64
 66  DIV_ACTUAL_ELAPSED_TIME  2906 non-null     float64
 67  DIV_ARR_DELAY            2906 non-null     float64
 68  DIV_DISTANCE             3906 non-null     float64
 69  DIV1_AIRPORT             4267 non-null     object
 70  DIV1_AIRPORT_ID          4267 non-null     float64
 71  DIV1_AIRPORT_SEQ_ID      4267 non-null     float64
 72  DIV1_WHEELS_ON           4267 non-null     float64
 73  DIV1_TOTAL_GTIME         4267 non-null     float64
 74  DIV1_LONGEST_GTIME       4267 non-null     float64
 75  DIV1_WHEELS_OFF          2938 non-null     float64
 76  DIV1_TAIL_NUM            2938 non-null     object
 77  Unnamed: 77              0 non-null        float64
dtypes: float64(40), int64(21), object(17)
memory usage: 1.0+ GB

In [6]:
#report = flight_data.profile_report(sort='None', html={'style':{'full_width': True}})
#report

In [7]:
pd.options.display.max_rows = 100

In [8]:
# Call the describe() method on flight_data to get the summary statistics
flight_data.describe().T

,count,mean,std,min,25%,50%,75%,max
YEAR,1749234.0,2.019000e+03,0.000000,2019.0,2019.0,2019.0,2019.00,2019.0
QUARTER,1749234.0,1.000000e+00,0.000000,1.0,1.0,1.0,1.00,1.0
MONTH,1749234.0,2.027491e+00,0.833331,1.0,1.0,2.0,3.00,3.0
DAY_OF_MONTH,1749234.0,1.562263e+01,8.698703,1.0,8.0,16.0,23.00,31.0
DAY_OF_WEEK,1749234.0,3.965747e+00,1.974492,1.0,2.0,4.0,6.00,7.0
OP_CARRIER_AIRLINE_ID,1749234.0,1.998393e+04,376.702844,19393.0,19790.0,19977.0,20368.00,20452.0
OP_CARRIER_FL_NUM,1749234.0,2.538028e+03,1811.782787,1.0,993.0,2127.0,3896.00,7439.0
ORIGIN_AIRPORT_ID,1749234.0,1.265829e+04,1520.706271,10135.0,11292.0,12889.0,13970.00,16218.0
ORIGIN_AIRPORT_SEQ_ID,1749234.0,1.265833e+06,152070.377266,1013505.0,1129202.0,1288903.0,1397005.00,1621802.0
ORIGIN_CITY_MARKET_ID,1749234.0,3.175228e+04,1299.136661,30070.0,30713.0,31453.0,32467.00,35991.0
ORIGIN_STATE_FIPS,1749234.0,2.684763e+01,16.482151,1.0,12.0,26.0,42.00,78.0
ORIGIN_WAC,1749234.0,5.388407e+01,26.097844,1.0,34.0,44.0,81.00,93.0
DEST_AIRPORT_ID,1749234.0,1.265812e+04,1520.614096,10135.0,11292.0,12889.0,13970.00,16218.0
DEST_AIRPORT_SEQ_ID,1749234.0,1.265816e+06,152061.159926,1013505.0,1129202.0,1288903.0,1397005.00,1621802.0
DEST_CITY_MARKET_ID,1749234.0,3.175211e+04,1298.906528,30070.0,30713.0,31453.0,32467.00,35991.0
DEST_STATE_FIPS,1749234.0,2.684978e+01,16.482348,1.0,12.0,26.0,42.00,78.0
DEST_WAC,1749234.0,5.388376e+01,26.097662,1.0,34.0,44.0,81.00,93.0
CRS_DEP_TIME,1749234.0,1.328002e+03,487.876730,1.0,915.0,1320.0,1733.00,2359.0
DEP_TIME,1705735.0,1.335261e+03,499.864505,1.0,920.0,1330.0,1743.00,2400.0
DEP_DELAY,1705727.0,1.062429e+01,49.165799,-56.0,-6.0,-2.0,7.00,2672.0
DEP_DELAY_NEW,1705727.0,1.389532e+01,48.085936,0.0,0.0,0.0,7.00,2672.0
DEP_DEL15,1705727.0,1.856141e-01,0.388795,0.0,0.0,0.0,0.00,1.0
DEP_DELAY_GROUP,1705727.0,6.128824e-02,2.247130,-2.0,-1.0,-1.0,0.00,12.0
TAXI_OUT,1705049.0,1.792382e+01,10.457525,1.0,12.0,15.0,21.00,227.0
WHEELS_OFF,1705049.0,1.360793e+03,500.292408,1.0,936.0,1345.0,1758.00,2400.0
WHEELS_ON,1703688.0,1.475883e+03,526.402675,1.0,1055.0,1512.0,1916.00,2400.0
TAXI_IN,1703688.0,7.571999e+00,5.824367,1.0,4.0,6.0,9.00,282.0
CRS_ARR_TIME,1749234.0,1.497590e+03,512.351336,1.0,1109.0,1522.0,1924.00,2400.0
ARR_TIME,1703688.0,1.480484e+03,530.659493,1.0,1059.0,1515.0,1921.00,2400.0
ARR_DELAY,1700782.0,5.262896e+00,51.427140,-94.0,-15.0,-6.0,8.00,2649.0
ARR_DELAY_NEW,1700782.0,1.414780e+01,47.911498,0.0,0.0,0.0,8.00,2649.0
ARR_DEL15,1700782.0,1.946022e-01,0.395894,0.0,0.0,0.0,0.00,1.0
ARR_DELAY_GROUP,1700782.0,-1.892088e-01,2.399325,-2.0,-1.0,-1.0,0.00,12.0
CANCELLED,1749234.0,2.546543e-02,0.157534,0.0,0.0,0.0,0.00,1.0
DIVERTED,1749234.0,2.233549e-03,0.047208,0.0,0.0,0.0,0.00,1.0
CRS_ELAPSED_TIME,1749100.0,1.434352e+02,72.999318,5.0,90.0,125.0,175.00,948.0
ACTUAL_ELAPSED_TIME,1700782.0,1.385086e+02,73.288685,15.0,85.0,121.0,170.00,1604.0
AIR_TIME,1700782.0,1.130249e+02,71.405595,4.0,61.0,95.0,143.00,1557.0
FLIGHTS,1749234.0,1.000000e+00,0.000000,1.0,1.0,1.0,1.00,1.0
DISTANCE,1749234.0,8.006665e+02,588.871289,31.0,368.0,642.0,1042.00,4983.0
DISTANCE_GROUP,1749234.0,3.676860e+00,2.318391,1.0,2.0,3.0,5.00,11.0
CARRIER_DELAY,330976.0,2.105051e+01,66.310568,0.0,0.0,0.0,17.00,2592.0
WEATHER_DELAY,330976.0,3.962574e+00,35.969649,0.0,0.0,0.0,0.00,1521.0
NAS_DELAY,330976.0,1.621757e+01,37.226433,0.0,0.0,4.0,20.00,1516.0
SECURITY_DELAY,330976.0,1.107724e-01,3.887436,0.0,0.0,0.0,0.00,816.0
LATE_AIRCRAFT_DELAY,330976.0,2.607418e+01,52.821356,0.0,0.0,1.0,31.00,2206.0
FIRST_DEP_TIME,11670.0,1.286246e+03,516.862894,1.0,824.0,1241.0,1730.00,2400.0
TOTAL_ADD_GTIME,11670.0,3.634996e+01,30.451875,1.0,16.0,28.0,45.00,375.0
LONGEST_ADD_GTIME,11670.0,3.571465e+01,29.010655,1.0,16.0,28.0,44.00,246.0
DIV_AIRPORT_LANDINGS,1749234.0,4.109227e-03,0.137693,0.0,0.0,0.0,0.00,9.0
DIV_REACHED_DEST,3907.0,7.437932e-01,0.436593,0.0,0.0,1.0,1.00,1.0
DIV_ACTUAL_ELAPSED_TIME,2906.0,4.271752e+02,241.943287,48.0,272.0,347.0,493.00,1793.0
DIV_ARR_DELAY,2906.0,2.746855e+02,250.030835,21.0,127.0,184.0,294.00,1542.0
DIV_DISTANCE,3906.0,5.890476e+01,196.363317,0.0,0.0,0.0,11.00,2586.0
DIV1_AIRPORT_ID,4267.0,1.279153e+04,1612.380864,10135.0,11292.0,12889.0,14107.00,16218.0
DIV1_AIRPORT_SEQ_ID,4267.0,1.279156e+06,161237.905484,1013505.0,1129202.0,1288903.0,1410702.00,1621802.0
DIV1_WHEELS_ON,4267.0,1.474087e+03,549.138176,1.0,1117.5,1455.0,1926.00,2400.0
DIV1_TOTAL_GTIME,4267.0,2.994141e+01,28.247804,1.0,11.0,21.0,39.00,219.0
DIV1_LONGEST_GTIME,4267.0,2.446239e+01,25.476107,1.0,9.0,15.0,29.00,219.0
DIV1_WHEELS_OFF,2938.0,1.459455e+03,570.128162,1.0,1116.0,1455.5,1928.75,2400.0
Unnamed: 77,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### *Missing Values*

In [9]:
# Call isnull() and mean() on flight_data to get the percentage of missing values for each column
round(flight_data.isnull().mean()[flight_data.isnull().mean().gt(0.75)] * 100, 2)

CANCELLATION_CODE           97.45
CARRIER_DELAY               81.08
WEATHER_DELAY               81.08
NAS_DELAY                   81.08
SECURITY_DELAY              81.08
LATE_AIRCRAFT_DELAY         81.08
FIRST_DEP_TIME              99.33
TOTAL_ADD_GTIME             99.33
LONGEST_ADD_GTIME           99.33
DIV_REACHED_DEST            99.78
DIV_ACTUAL_ELAPSED_TIME     99.83
DIV_ARR_DELAY               99.83
DIV_DISTANCE                99.78
DIV1_AIRPORT                99.76
DIV1_AIRPORT_ID             99.76
DIV1_AIRPORT_SEQ_ID         99.76
DIV1_WHEELS_ON              99.76
DIV1_TOTAL_GTIME            99.76
DIV1_LONGEST_GTIME          99.76
DIV1_WHEELS_OFF             99.83
DIV1_TAIL_NUM               99.83
Unnamed: 77                100.00
dtype: float64

In [10]:
# Extract the columns with percentage of null values greater than 75% to a dataframe null_cols
null_cols = (flight_data.isnull().mean()[flight_data.isnull().mean().gt(0.75)] * 100).to_frame()

# Extract the column names to be dropped
cols_to_drop = list(null_cols.index)

In [11]:
# Call drop() method on flight data 
# to drop columns with more than 75% of null values
flight_data = flight_data.drop(cols_to_drop, axis = 1)

In [12]:
# Check for null values
flight_data.isnull().sum()[flight_data.isnull().sum().gt(0)]

TAIL_NUM                8004
DEP_TIME               43499
DEP_DELAY              43507
DEP_DELAY_NEW          43507
DEP_DEL15              43507
DEP_DELAY_GROUP        43507
TAXI_OUT               44185
WHEELS_OFF             44185
WHEELS_ON              45546
TAXI_IN                45546
ARR_TIME               45546
ARR_DELAY              48452
ARR_DELAY_NEW          48452
ARR_DEL15              48452
ARR_DELAY_GROUP        48452
CRS_ELAPSED_TIME         134
ACTUAL_ELAPSED_TIME    48452
AIR_TIME               48452
dtype: int64

*'CRS_ELAPSED_TIME' - "Estmated time an airplane spends in the air, as opposed to time spent taxiing to and from the gate and during stopovers.*  

*Has 135 missing values that could be imputed or dropped..since the null value count is too small when comapred to the dataset we have, we can drop the nulls*

In [13]:
# Drop the rows with null values for column CRS_ELAPSED_TIME 
flight_data.dropna(subset = ['CRS_ELAPSED_TIME'], inplace = True)

### *Drop dataframe columns with only one distinct value*

In [14]:
cols = flight_data.columns[flight_data.nunique() == 1]
cols

Index(['YEAR', 'QUARTER', 'FLIGHTS'], dtype='object')

In [15]:
flight_data = flight_data.drop(cols, axis=1)

In [16]:
flight_data.head()

,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,...,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,DISTANCE_GROUP,DIV_AIRPORT_LANDINGS
0,1,3,4,2019-01-03,9E,20363,9E,N195PQ,5121,15412,...,1.0,1200-1259,0.0,0.0,70.0,70.0,36.0,152.0,1,0
1,1,4,5,2019-01-04,9E,20363,9E,N919XJ,5121,15412,...,5.0,1200-1259,0.0,0.0,70.0,82.0,38.0,152.0,1,0
2,1,5,6,2019-01-05,9E,20363,9E,N316PQ,5122,10397,...,-1.0,1000-1059,0.0,0.0,121.0,107.0,84.0,563.0,3,0
3,1,6,7,2019-01-06,9E,20363,9E,N325PQ,5122,10397,...,-2.0,1000-1059,0.0,0.0,123.0,104.0,85.0,563.0,3,0
4,1,7,1,2019-01-07,9E,20363,9E,N904XJ,5122,10397,...,-1.0,1000-1059,0.0,0.0,123.0,117.0,88.0,563.0,3,0

In [17]:
# Get the shape of flight_data
flight_data.shape

(1749100, 53)

### *Duplicates*

In [18]:
# Find the duplicate rows
duplicates = flight_data.duplicated()

In [19]:
flight_data[duplicates]

Empty DataFrame
Columns: [MONTH, DAY_OF_MONTH, DAY_OF_WEEK, FL_DATE, OP_UNIQUE_CARRIER, OP_CARRIER_AIRLINE_ID, OP_CARRIER, TAIL_NUM, OP_CARRIER_FL_NUM, ORIGIN_AIRPORT_ID, ORIGIN_AIRPORT_SEQ_ID, ORIGIN_CITY_MARKET_ID, ORIGIN, ORIGIN_CITY_NAME, ORIGIN_STATE_ABR, ORIGIN_STATE_FIPS, ORIGIN_STATE_NM, ORIGIN_WAC, DEST_AIRPORT_ID, DEST_AIRPORT_SEQ_ID, DEST_CITY_MARKET_ID, DEST, DEST_CITY_NAME, DEST_STATE_ABR, DEST_STATE_FIPS, DEST_STATE_NM, DEST_WAC, CRS_DEP_TIME, DEP_TIME, DEP_DELAY, DEP_DELAY_NEW, DEP_DEL15, DEP_DELAY_GROUP, DEP_TIME_BLK, TAXI_OUT, WHEELS_OFF, WHEELS_ON, TAXI_IN, CRS_ARR_TIME, ARR_TIME, ARR_DELAY, ARR_DELAY_NEW, ARR_DEL15, ARR_DELAY_GROUP, ARR_TIME_BLK, CANCELLED, DIVERTED, CRS_ELAPSED_TIME, ACTUAL_ELAPSED_TIME, AIR_TIME, DISTANCE, DISTANCE_GROUP, DIV_AIRPORT_LANDINGS]
Index: []

[0 rows x 53 columns]

### *DateTime Object*

In [20]:
# Convert 'FL_DATE' column from string to datetime
flight_data['FL_DATE'] = pd.to_datetime(flight_data['FL_DATE']) #.dt.date

In [21]:
flight_data.head().T

,0,1,2,3,4
MONTH,1,1,1,1,1
DAY_OF_MONTH,3,4,5,6,7
DAY_OF_WEEK,4,5,6,7,1
FL_DATE,2019-01-03 00:00:00,2019-01-04 00:00:00,2019-01-05 00:00:00,2019-01-06 00:00:00,2019-01-07 00:00:00
OP_UNIQUE_CARRIER,9E,9E,9E,9E,9E
OP_CARRIER_AIRLINE_ID,20363,20363,20363,20363,20363
OP_CARRIER,9E,9E,9E,9E,9E
TAIL_NUM,N195PQ,N919XJ,N316PQ,N325PQ,N904XJ
OP_CARRIER_FL_NUM,5121,5121,5122,5122,5122
ORIGIN_AIRPORT_ID,15412,15412,10397,10397,10397
ORIGIN_AIRPORT_SEQ_ID,1541205,1541205,1039707,1039707,1039707
ORIGIN_CITY_MARKET_ID,35412,35412,30397,30397,30397
ORIGIN,TYS,TYS,ATL,ATL,ATL
ORIGIN_CITY_NAME,"Knoxville, TN","Knoxville, TN","Atlanta, GA","Atlanta, GA","Atlanta, GA"
ORIGIN_STATE_ABR,TN,TN,GA,GA,GA
ORIGIN_STATE_FIPS,47,47,13,13,13
ORIGIN_STATE_NM,Tennessee,Tennessee,Georgia,Georgia,Georgia
ORIGIN_WAC,54,54,34,34,34
DEST_AIRPORT_ID,10397,10397,14783,14783,14783
DEST_AIRPORT_SEQ_ID,1039707,1039707,1478302,1478302,1478302
DEST_CITY_MARKET_ID,30397,30397,34783,34783,34783
DEST,ATL,ATL,SGF,SGF,SGF
DEST_CITY_NAME,"Atlanta, GA","Atlanta, GA","Springfield, MO","Springfield, MO","Springfield, MO"
DEST_STATE_ABR,GA,GA,MO,MO,MO
DEST_STATE_FIPS,13,13,29,29,29
DEST_STATE_NM,Georgia,Georgia,Missouri,Missouri,Missouri
DEST_WAC,34,34,64,64,64
CRS_DEP_TIME,1140,1140,950,950,950
DEP_TIME,1205,1250,956,945,947
DEP_DELAY,25,70,6,-5,-3
DEP_DELAY_NEW,25,70,6,0,0
DEP_DEL15,1,1,0,0,0
DEP_DELAY_GROUP,1,4,0,-1,-1
DEP_TIME_BLK,1100-1159,1100-1159,0900-0959,0900-0959,0900-0959
TAXI_OUT,30,35,20,16,25
WHEELS_OFF,1235,1325,1016,1001,1012
WHEELS_ON,1311,1403,1040,1026,1040
TAXI_IN,4,9,3,3,4
CRS_ARR_TIME,1250,1250,1051,1053,1053
ARR_TIME,1315,1412,1043,1029,1044
ARR_DELAY,25,82,-8,-24,-9
ARR_DELAY_NEW,25,82,0,0,0
ARR_DEL15,1,1,0,0,0
ARR_DELAY_GROUP,1,5,-1,-2,-1
ARR_TIME_BLK,1200-1259,1200-1259,1000-1059,1000-1059,1000-1059
CANCELLED,0,0,0,0,0
DIVERTED,0,0,0,0,0
CRS_ELAPSED_TIME,70,70,121,123,123
ACTUAL_ELAPSED_TIME,70,82,107,104,117
AIR_TIME,36,38,84,85,88
DISTANCE,152,152,563,563,563
DISTANCE_GROUP,1,1,3,3,3
DIV_AIRPORT_LANDINGS,0,0,0,0,0

### *Save clean datafarame to csv*

In [22]:
#Save clean dataframe to csv
flight_data.to_csv('02_flight_data_cleaned.csv', index = False)